[CmdletBinding()]
param(
  [string]$ConfigPath = (Join-Path (Split-Path -Parent $PSScriptRoot) "config\\cli-proxy-config.yaml"),
  [string]$RuntimeDir = (Join-Path (Split-Path -Parent $PSScriptRoot) ".runtime"),
  [string]$ContainerName = "cliproxyapi-claude-gateway",
  [string]$ImageTag = "cliproxyapi-wrapper:v6.9.16",
  [string]$GoImage = "docker.m.daocloud.io/library/golang:1.26-alpine",
  [string]$RunnerImage = "docker.m.daocloud.io/library/alpine:3.22.0",
  [string]$GoProxy = "https://goproxy.cn,direct",
  [string]$GoSumDb = "sum.golang.google.cn",
  [switch]$SkipBuild,
  [switch]$ForceBuild,
  [switch]$ForceRecreate,
  [int]$HealthCheckTimeoutSec = 180,
  [int]$HealthCheckIntervalSec = 5
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Import-DotEnv {
  param([Parameter(Mandatory = $true)][string]$Path)

  if (-not (Test-Path -LiteralPath $Path)) {
    return
  }

  Get-Content -LiteralPath $Path | ForEach-Object {
    $line = $_.Trim()
    if (-not $line) { return }
    if ($line.StartsWith("#")) { return }
    $parts = $line -split "=", 2
    if ($parts.Count -ne 2) { return }
    $key = $parts[0].Trim()
    $value = $parts[1].Trim()
    if ($key) {
      [Environment]::SetEnvironmentVariable($key, $value, "Process")
    }
  }
}

function Get-ConfigScalar {
  param(
    [Parameter(Mandatory = $true)][string]$Path,
    [Parameter(Mandatory = $true)][string]$Key
  )

  foreach ($line in Get-Content -LiteralPath $Path) {
    if ($line -match "^\s*$Key\s*:\s*(.*)$") {
      return $Matches[1].Trim().Trim('"').Trim("'")
    }
  }

  return ""
}

function Get-ExistingContainerId {
  param([Parameter(Mandatory = $true)][string]$Name)

  $result = docker ps -aq --filter "name=^$Name$"
  if ($LASTEXITCODE -ne 0) {
    throw "Failed to inspect existing Docker containers."
  }
  return [string]$result
}

function ConvertTo-YamlSingleQuoted {
  param([AllowNull()][string]$Value)

  if ($null -eq $Value) {
    return "''"
  }

  return "'" + ($Value -replace "'", "''") + "'"
}

function Get-BoolEnvValue {
  param(
    [Parameter(Mandatory = $true)][string]$Name,
    [bool]$Default = $false
  )

  $raw = [Environment]::GetEnvironmentVariable($Name, "Process")
  if ([string]::IsNullOrWhiteSpace($raw)) {
    return $Default
  }

  switch ($raw.Trim().ToLowerInvariant()) {
    "1" { return $true }
    "true" { return $true }
    "yes" { return $true }
    "on" { return $true }
    "0" { return $false }
    "false" { return $false }
    "no" { return $false }
    "off" { return $false }
    default { return $Default }
  }
}

function Get-JsonScalarProperty {
  param(
    [Parameter(Mandatory = $true)][string]$Path,
    [Parameter(Mandatory = $true)][string]$PropertyName
  )

  if (-not (Test-Path -LiteralPath $Path)) {
    return ""
  }

  try {
    $payload = Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json -Depth 20
    $property = $payload.PSObject.Properties[$PropertyName]
    if ($property -and $property.Value) {
      return [string]$property.Value
    }
  } catch {
    return ""
  }

  return ""
}

function Resolve-CodexApiKeyBootstrap {
  $baseUrl = if ($env:CLI_PROXY_API_CODEX_BASE_URL) {
    $env:CLI_PROXY_API_CODEX_BASE_URL.Trim()
  } elseif ($env:OPENAI_BASE_URL) {
    $env:OPENAI_BASE_URL.Trim()
  } else {
    "https://api.openai.com"
  }

  if ($env:OPENAI_API_KEY) {
    return [PSCustomObject]@{
      api_key = $env:OPENAI_API_KEY.Trim()
      base_url = $baseUrl
      source = "OPENAI_API_KEY"
    }
  }

  if (-not (Get-BoolEnvValue -Name "CLI_PROXY_API_USE_LOCAL_CODEX_AUTH_JSON" -Default $true)) {
    return $null
  }

  $localAuthPath = Join-Path $env:USERPROFILE ".codex\\auth.json"
  $localApiKey = Get-JsonScalarProperty -Path $localAuthPath -PropertyName "OPENAI_API_KEY"
  if ($localApiKey) {
    return [PSCustomObject]@{
      api_key = $localApiKey.Trim()
      base_url = $baseUrl
      source = $localAuthPath
    }
  }

  return $null
}

function New-RuntimeConfig {
  param(
    [Parameter(Mandatory = $true)][string]$SourceConfigPath,
    [Parameter(Mandatory = $true)][string]$DestinationPath,
    [AllowNull()][object]$CodexBootstrap,
    [bool]$EnableCodexWebsockets = $false
  )

  $content = Get-Content -LiteralPath $SourceConfigPath -Raw
  if (-not $content.EndsWith("`n")) {
    $content += "`r`n"
  }

  $overlayLines = [System.Collections.Generic.List[string]]::new()
  $overlayLines.Add("")
  $overlayLines.Add("# Generated by start-cliproxyapi.ps1. Do not edit this file directly.")

  if ($CodexBootstrap) {
    $overlayLines.Add("codex-api-key:")
    $overlayLines.Add("  - api-key: " + (ConvertTo-YamlSingleQuoted -Value ([string]$CodexBootstrap.api_key)))
    $overlayLines.Add("    base-url: " + (ConvertTo-YamlSingleQuoted -Value ([string]$CodexBootstrap.base_url)))
    if ($EnableCodexWebsockets) {
      $overlayLines.Add("    websockets: true")
    }
    $overlayLines.Add("    models:")
    foreach ($modelName in @("gpt-5.4", "gpt-5", "gpt-5-codex")) {
      $overlayLines.Add("      - name: " + (ConvertTo-YamlSingleQuoted -Value $modelName))
      $overlayLines.Add("        alias: " + (ConvertTo-YamlSingleQuoted -Value $modelName))
    }
  }

  $generatedContent = $content + ($overlayLines -join "`r`n") + "`r`n"
  Set-Content -LiteralPath $DestinationPath -Value $generatedContent -Encoding UTF8
}

$root = Split-Path -Parent $PSScriptRoot
$vendorDir = Join-Path $root "vendor\\CLIProxyAPI"
$dockerfilePath = Join-Path $root "docker\\Dockerfile.cliproxyapi"
$envPath = Join-Path $root ".env"
$resolvedConfigPath = (Resolve-Path -LiteralPath $ConfigPath).Path
$runtimeDirAbsolute = [System.IO.Path]::GetFullPath($RuntimeDir)
$authDir = Join-Path $runtimeDirAbsolute "auths"
$logsDir = Join-Path $runtimeDirAbsolute "logs"
$statePath = Join-Path $runtimeDirAbsolute "cliproxyapi-state.json"

if (-not (Test-Path -LiteralPath $vendorDir)) {
  throw "Missing vendored CLIProxyAPI directory: $vendorDir"
}
if (-not (Test-Path -LiteralPath $dockerfilePath)) {
  throw "Missing wrapper Dockerfile: $dockerfilePath"
}
if (-not (Test-Path -LiteralPath $ConfigPath)) {
  throw "Missing config file: $ConfigPath"
}

Import-DotEnv -Path (Join-Path $root ".env.example")
Import-DotEnv -Path $envPath

if ($env:CLI_PROXY_API_CONTAINER_NAME) {
  $ContainerName = $env:CLI_PROXY_API_CONTAINER_NAME
}
if ($env:CLI_PROXY_API_IMAGE_TAG) {
  $ImageTag = $env:CLI_PROXY_API_IMAGE_TAG
}
if ($env:CLI_PROXY_API_GO_IMAGE) {
  $GoImage = $env:CLI_PROXY_API_GO_IMAGE
}
if ($env:CLI_PROXY_API_RUNNER_IMAGE) {
  $RunnerImage = $env:CLI_PROXY_API_RUNNER_IMAGE
}
if ($env:CLI_PROXY_API_GOPROXY) {
  $GoProxy = $env:CLI_PROXY_API_GOPROXY
}
if ($env:CLI_PROXY_API_GOSUMDB) {
  $GoSumDb = $env:CLI_PROXY_API_GOSUMDB
}

docker --version | Out-Null
if ($LASTEXITCODE -ne 0) {
  throw "Docker is not available. Install Docker Desktop or adjust the startup strategy."
}

$configuredPort = Get-ConfigScalar -Path $ConfigPath -Key "port"
if (-not $configuredPort) {
  throw "Config file is missing a top-level port value: $ConfigPath"
}

$endpointHost = if ($env:CLI_PROXY_API_HOST) { $env:CLI_PROXY_API_HOST } else { "127.0.0.1" }
$publishHost = if ([string]::IsNullOrWhiteSpace($endpointHost)) { "127.0.0.1" } else { $endpointHost.Trim() }
$endpointPort = if ($env:CLI_PROXY_API_PORT) { $env:CLI_PROXY_API_PORT } else { $configuredPort }
$gatewayUrl = if ($env:CLI_PROXY_API_ENDPOINT) { $env:CLI_PROXY_API_ENDPOINT.TrimEnd("/") } else { "http://$publishHost`:$endpointPort" }
$enableCodexWebsockets = Get-BoolEnvValue -Name "CLI_PROXY_API_CODEX_WEBSOCKETS" -Default $false

New-Item -ItemType Directory -Force -Path $runtimeDirAbsolute | Out-Null
New-Item -ItemType Directory -Force -Path $authDir | Out-Null
New-Item -ItemType Directory -Force -Path $logsDir | Out-Null

$generatedConfigPath = Join-Path $runtimeDirAbsolute "generated-config.yaml"
$codexBootstrap = Resolve-CodexApiKeyBootstrap
New-RuntimeConfig -SourceConfigPath $resolvedConfigPath -DestinationPath $generatedConfigPath -CodexBootstrap $codexBootstrap -EnableCodexWebsockets $enableCodexWebsockets

$existingContainerId = Get-ExistingContainerId -Name $ContainerName
if ($existingContainerId) {
  if (-not $ForceRecreate.IsPresent) {
    Write-Host "Container already exists: $ContainerName"
    Write-Host "Use -ForceRecreate to replace it."
    exit 0
  }

  Write-Host "Removing existing container: $ContainerName"
  docker rm -f $ContainerName | Out-Null
  if ($LASTEXITCODE -ne 0) {
    throw "Failed to remove existing container: $ContainerName"
  }
}

docker image inspect $ImageTag *> $null
$imageExists = ($LASTEXITCODE -eq 0)

if ($SkipBuild.IsPresent) {
  Write-Host "[1/3] Skip build enabled. Using existing image: $ImageTag"
} elseif ($imageExists -and -not $ForceBuild.IsPresent) {
  Write-Host "[1/3] Existing image detected. Skipping rebuild: $ImageTag"
} else {
  Write-Host "[1/3] Building pinned CLIProxyAPI image: $ImageTag"
  docker build -f $dockerfilePath -t $ImageTag --build-arg "GO_IMAGE=$GoImage" --build-arg "RUNNER_IMAGE=$RunnerImage" --build-arg "GOPROXY=$GoProxy" --build-arg "GOSUMDB=$GoSumDb" --build-arg "VERSION=v6.9.16" --build-arg "COMMIT=c8b7e2b8d6f24462b724925dfe4f984ae6b9e302" --build-arg ("BUILD_DATE=" + (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")) $root
  if ($LASTEXITCODE -ne 0) {
    throw "Docker build failed for $ImageTag"
  }
}

Write-Host "[2/3] Starting container: $ContainerName"
$dockerArgs = @(
  "run", "-d",
  "--name", $ContainerName,
  "-p", "${publishHost}:$endpointPort`:$configuredPort",
  "-p", "${publishHost}:1455:1455",
  "-p", "${publishHost}:54545:54545",
  "-p", "${publishHost}:8085:8085",
  "-p", "${publishHost}:51121:51121",
  "-p", "${publishHost}:11451:11451",
  "-v", "${generatedConfigPath}:/CLIProxyAPI/config.yaml",
  "-v", "${authDir}:/root/.cli-proxy-api",
  "-v", "${logsDir}:/CLIProxyAPI/logs",
  $ImageTag
)
docker @dockerArgs | Out-Null
if ($LASTEXITCODE -ne 0) {
  throw "Docker run failed for container $ContainerName"
}

Write-Host "[3/3] Waiting for gateway health..."
$deadline = (Get-Date).AddSeconds($HealthCheckTimeoutSec)
$lastError = ""
$healthy = $false
while ((Get-Date) -lt $deadline) {
  try {
    $response = Invoke-WebRequest -Uri "$gatewayUrl/" -Method Get -TimeoutSec 10 -SkipHttpErrorCheck
    if ($response.StatusCode -ge 200 -and $response.StatusCode -lt 300) {
      $healthy = $true
      break
    }
    $lastError = "HTTP $([int]$response.StatusCode)"
  } catch {
    $lastError = $_.Exception.Message
  }
  Start-Sleep -Seconds $HealthCheckIntervalSec
}

if (-not $healthy) {
  Write-Warning "Gateway did not become healthy in time."
  if ($lastError) {
    Write-Warning "Last error: $lastError"
  }
  Write-Warning "Recent container logs:"
  docker logs --tail 120 $ContainerName
  throw "CLIProxyAPI gateway failed to start cleanly."
}

$state = [PSCustomObject]@{
  container_name = $ContainerName
  image_tag = $ImageTag
  endpoint = $gatewayUrl
  port = [int]$endpointPort
  config_path = $generatedConfigPath
  base_config_path = $resolvedConfigPath
  auth_dir = $authDir
  logs_dir = $logsDir
  codex_api_key_source = if ($codexBootstrap) { [string]$codexBootstrap.source } else { "" }
  started_at = (Get-Date).ToString("o")
}
$state | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath $statePath -Encoding UTF8

Write-Host ""
Write-Host "CLIProxyAPI gateway is ready."
Write-Host "Endpoint    : $gatewayUrl"
Write-Host "Container   : $ContainerName"
Write-Host "Image       : $ImageTag"
Write-Host "Go image    : $GoImage"
Write-Host "Runner image: $RunnerImage"
Write-Host "Bind host   : $publishHost"
Write-Host "GOPROXY     : $GoProxy"
Write-Host "GOSUMDB     : $GoSumDb"
Write-Host "Base config : $resolvedConfigPath"
Write-Host "Run config  : $generatedConfigPath"
if ($codexBootstrap) {
  Write-Host "Codex auth  : API key bootstrap from $($codexBootstrap.source)"
} else {
  Write-Host "Codex auth  : no API key bootstrap detected; OAuth/login is still required"
}
Write-Host "State file  : $statePath"
